(async function(){
'use strict';
const S=window.SWLShop;if(!S)return;document.getElementById('checkout-address')?.addEventListener('submit',e=>e.preventDefault());await S.ready;
const $=id=>document.getElementById(id);
async function api(path,body){const r=await fetch('/shop/api/'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,cache:'no-store'});let data;try{data=await r.json();}catch(e){throw Error('Checkout could not connect. Please try again.');}if(!r.ok)throw Error(data.error||'Checkout could not complete this request.');return data;}
function summaryItems(cart){return cart.map(r=>`<div class="swl-checkout-mini"><strong>${r.quantity} × ${S.esc(r.kind==='birthday'?'Birthday Box (10 kits)':S.name(r))}</strong><span> · ${S.money(S.unitPrice(r)*r.quantity)}</span><small>${S.esc(r.kind==='birthday'?'Ten friends with your selected extras':S.description(r))}</small></div>`).join('');}
const PENDING_KEY='swl-pending-order-v1';
function rememberPending(order){try{sessionStorage.setItem(PENDING_KEY,JSON.stringify(order));}catch(e){}}
function forgetPending(){try{sessionStorage.removeItem(PENDING_KEY);}catch(e){}}
const receipt=$('receipt-status');
if(receipt){(async()=>{try{const params=new URLSearchParams(location.search);const id=params.get('order');const token=params.get('key');if(!id||!token)throw Error('No order reference was provided. Please use the confirmation link from your checkout.');const d=await api('order?id='+encodeURIComponent(id)+'&key='+encodeURIComponent(token));if(d.status!=='paid')throw Error(d.status==='processing'?'Your payment is still being checked. Please refresh this page shortly.':'Payment is not confirmed. Please contact us before placing the order again.');$('receipt-heading').textContent=d.test?'Your practice order worked!':'Your crew is on its way to becoming yours!';receipt.textContent=d.test?'This was a test payment. No real money was charged and no package will be shipped.':'Your payment is confirmed. Thank you for supporting our family business! We’ll prepare your new friends for shipping.';const address=d.address;$('receipt-details').innerHTML=`<p><strong>Order ${S.esc(d.id)}</strong><br>Total: ${S.money(d.total)}</p>${summaryItems(d.cart)}<p>${S.esc(address.name)}<br>${S.esc(address.street1)} ${S.esc(address.street2)}<br>${S.esc(address.city)}, ${S.esc(address.state)} ${S.esc(address.zip)}</p><p class="swl-fine">Save this confirmation link for your records. Questions? Email hello@stuffedwithlovegb.com and include your order number.</p>`;if(d.receiptUrl&&/^https:\/\//.test(d.receiptUrl)){const a=document.createElement('a');a.href=d.receiptUrl;a.textContent='View your Square receipt';a.target='_blank';a.rel='noopener';$('receipt-details').append(a);}}catch(e){$('receipt-heading').textContent='Let’s check your order.';receipt.textContent=e.message;}})();return;}
if(!$('checkout-address'))return;
let payments=null;
let config,quote=null,selected=null,card=null,cardReady=false,busy=false,paymentStarted=false,activeOrder=null,cartSnapshot=JSON.stringify(S.getCart());
const states='AL:Alabama,AK:Alaska,AZ:Arizona,AR:Arkansas,CA:California,CO:Colorado,CT:Connecticut,DE:Delaware,DC:District of Columbia,FL:Florida,GA:Georgia,HI:Hawaii,ID:Idaho,IL:Illinois,IN:Indiana,IA:Iowa,KS:Kansas,KY:Kentucky,LA:Louisiana,ME:Maine,MD:Maryland,MA:Massachusetts,MI:Michigan,MN:Minnesota,MS:Mississippi,MO:Missouri,MT:Montana,NE:Nebraska,NV:Nevada,NH:New Hampshire,NJ:New Jersey,NM:New Mexico,NY:New York,NC:North Carolina,ND:North Dakota,OH:Ohio,OK:Oklahoma,OR:Oregon,PA:Pennsylvania,RI:Rhode Island,SC:South Carolina,SD:South Dakota,TN:Tennessee,TX:Texas,UT:Utah,VT:Vermont,VA:Virginia,WA:Washington,WV:West Virginia,WI:Wisconsin,WY:Wyoming';
$('checkout-state').insertAdjacentHTML('beforeend',states.split(',').map(s=>{const [v,n]=s.split(':');return `<option value="${v}">${n}</option>`;}).join(''));
$('get-shipping').disabled=true;
$('checkout-items').innerHTML=summaryItems(S.getCart());$('checkout-subtotal').textContent=S.money(S.subtotal());
function status(s){$('checkout-status').textContent=s;}
function canPay(){ $('pay-button').disabled=paymentStarted?busy:(busy||!selected||!cardReady||!$('order-agree').checked); }
function invalidate(){if(paymentStarted)return;quote=null;selected=null;$('shipping-section').hidden=true;$('payment-section').hidden=true;$('checkout-shipping').textContent='Choose delivery';$('checkout-tax').textContent='Calculated with delivery';$('checkout-total').textContent='—';canPay();}
function totals(){if(!selected)return;const tax=selected.tax;const total=quote.subtotal+selected.amount+tax;$('checkout-shipping').textContent=S.money(selected.amount);$('checkout-tax').textContent=S.money(tax);$('checkout-total').textContent=S.money(total);$('pay-button').textContent=(config.test?'Place practice order · ':'Pay ')+S.money(total);}
try{activeOrder=JSON.parse(sessionStorage.getItem(PENDING_KEY)||'null');if(activeOrder?.id&&activeOrder?.key){paymentStarted=true;$('checkout-address').querySelectorAll('input,select,button').forEach(el=>el.disabled=true);$('payment-section').hidden=false;$('pay-button').textContent='Check payment status';$('pay-button').disabled=false;checkPending().then(()=>{if(paymentStarted)$('pay-button').disabled=false;});}}catch(e){}
function loadSDK(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>reject(Error('Square’s payment form could not load. Please try again.'));document.head.append(s);});}
(async()=>{try{if(!S.catalogReady)throw Error('The shop could not check product availability. Please refresh checkout.');if(!S.getCart().length)throw Error('Your cart is empty. Choose a friend before checking out.');if(S.getCart().some(r=>!S.available(r)))throw Error('A selected friend is no longer available. Return to your cart to update your selections.');config=await api('config');$('checkout-mode').textContent=config.test?'Practice checkout: no real payment will be charged or order shipped.':'Secure checkout powered by Square.';if(!config.ready)throw Error(config.message||'Checkout is not ready yet. Please contact us.');await loadSDK(config.test?'https://sandbox.web.squarecdn.com/v1/square.js':'https://web.squarecdn.com/v1/square.js');payments=window.Square.payments(config.applicationId,config.locationId);if(!paymentStarted)$('get-shipping').disabled=false;$('payment-test-copy').textContent=config.test?'For testing, use card 4111 1111 1111 1111, any future expiration, CVV 111, and ZIP 54304. Do not use your actual card.':'';canPay();}catch(e){$('get-shipping').disabled=true;status(e.message);}})();
$('checkout-address').addEventListener('input',invalidate);
window.addEventListener('swl-cart-change',()=>{if(paymentStarted)return;if(cartSnapshot!==JSON.stringify(S.getCart())){cartSnapshot=JSON.stringify(S.getCart());invalidate();$('checkout-items').innerHTML=summaryItems(S.getCart());$('checkout-subtotal').textContent=S.money(S.subtotal());status('Your cart changed. Please request shipping options again.');}});
$('checkout-address').addEventListener('submit',async e=>{e.preventDefault();if(busy||paymentStarted||!config?.ready)return;busy=true;invalidate();$('get-shipping').disabled=true;status('Checking your address, shipping options, and tax…');try{const address=Object.fromEntries(new FormData(e.target));quote=await api('quote',{cart:S.getCart(),address});$('checkout-subtotal').textContent=S.money(quote.subtotal);$('checkout-items').innerHTML=summaryItems(quote.cart||S.getCart());$('shipping-options').innerHTML=quote.rates.map(r=>`<label class="swl-shipping-option"><input type="radio" name="delivery" value="${S.esc(r.id)}"><span><strong>${S.esc(r.provider)} · ${S.esc(r.service)}</strong><small>${r.days?'Estimated '+r.days+' business days':'Transit estimate unavailable'}</small></span><strong>${S.money(r.amount)}</strong></label>`).join('');$('shipping-section').hidden=false;status(config.test?'Practice shipping options are ready. Choose one below.':'Choose a shipping option below.');}catch(err){status(err.message);}finally{busy=false;$('get-shipping').disabled=false;canPay();}});
$('shipping-options').addEventListener('change',async e=>{if(!quote)return;selected=quote.rates.find(r=>r.id===e.target.value);$('payment-section').hidden=false;totals();canPay();try{if(!card){card=await payments.card();await card.attach('#square-card');cardReady=true;}canPay();}catch(err){card=null;status('The payment form could not load. Please refresh checkout and try again.');}});
$('order-agree').addEventListener('change',canPay);
function redirect(d){forgetPending();if(!d.id||!d.key)throw Error('Missing confirmation reference. Please contact us.');S.clear();location.assign('order-received.html?order='+encodeURIComponent(d.id)+'&key='+encodeURIComponent(d.key));}
async function checkPending(){if(!activeOrder)return;try{const d=await api('order?id='+encodeURIComponent(activeOrder.id)+'&key='+encodeURIComponent(activeOrder.key));if(d.status==='paid'){redirect({...d,key:activeOrder.key});return;}if(d.status==='failed'){forgetPending();paymentStarted=false;activeOrder=null;$('checkout-address').querySelectorAll('input,select,button').forEach(el=>el.disabled=false);invalidate();status(d.status==='failed'?'Your payment was not completed. Request shipping options again to try another card.':'No payment was submitted for that checkout. Request shipping options again.');return;}status('Payment confirmation is still pending. Do not place another order. Use Check payment status again, or contact us with order '+activeOrder.id+'.');}catch(e){status('Could not check your payment yet. Do not place another order. Reference: '+activeOrder.id);} }
$('pay-button').addEventListener('click',async()=>{if(busy)return;if(paymentStarted){busy=true;await checkPending();busy=false;if(!paymentStarted)canPay();return;}if(!selected||!quote||!$('order-agree').checked||!card)return;if(JSON.stringify(S.getCart())!==cartSnapshot){invalidate();status('Your cart changed. Please request shipping options again.');return;}busy=true;canPay();status('Processing securely…');try{
const names=quote.address.name.trim().split(/\s+/);const result=await card.tokenize({amount:((quote.subtotal+selected.amount+selected.tax)/100).toFixed(2),currencyCode:'USD',intent:'CHARGE',customerInitiated:true,sellerKeyedIn:false,billingContact:{givenName:names[0],familyName:names.slice(1).join(' '),email:quote.address.email,addressLines:[quote.address.street1,quote.address.street2].filter(Boolean),city:quote.address.city,state:quote.address.state,postalCode:quote.address.zip,countryCode:'US'}});
if(result.status!=='OK')throw Error(result.errors?.map(x=>x.message).join(' ')||'Please check your card details.');
const prepared=await api('prepare',{quoteId:quote.id,rateId:selected.id});activeOrder={id:prepared.id,key:prepared.key};rememberPending(activeOrder);paymentStarted=true;
$('checkout-address').querySelectorAll('input,select,button').forEach(el=>el.disabled=true);$('shipping-options').querySelectorAll('input').forEach(el=>el.disabled=true);
const response=await api('pay',{id:prepared.id,key:prepared.key,sourceId:result.token});if(response.status==='paid'){redirect({...response,key:prepared.key});return;}throw Error('Payment confirmation is pending.');
}catch(err){if(paymentStarted){await checkPending();if(paymentStarted){$('pay-button').textContent='Check payment status';$('pay-button').disabled=false;}}else status(err.message);}finally{busy=false;if(!paymentStarted)canPay();}
});
})();
